Resources:
  AppSyncLambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.appSync.serviceRole}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ${self:custom.appSync.serviceRole}Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:invokeFunction
                Resource:
                  - { Fn::GetAtt: [ListDataLambdaFunction, Arn] }
                  - { Fn::GetAtt: [CreateDataLambdaFunction, Arn] }
