resources:
  Resources:
    AssetStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: gopato-cloud-services-${self:custom.stage}-asset-storage
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: [HEAD, GET, PUT, POST, DELETE]
              AllowedOrigins: ["*"]
              ExposedHeaders:
                [
                  x-amz-server-side-encryption,
                  x-amz-request-id,
                  x-amz-id-2,
                  ETag,
                ]
              MaxAge: 3000
